package com.example.BookingService.Data.mapper;

import com.example.BookingService.Data.entity.ServicesEntity;
import com.example.BookingService.Domain.dto.ServicesRequestDTO;
import com.example.BookingService.Domain.dto.ServicesResponseDTO;
import com.example.BookingService.Domain.model.ServicesModel;
import org.springframework.stereotype.Component;

@Component
public class ServicesMapper {

    // --- 1. Entity -> Domain Model (For internal Service Logic) ---
    public ServicesModel toDomain(ServicesEntity entity) {
        ServicesModel model = new ServicesModel();
        model.setId(entity.getService_id());
        model.setName(entity.getService_name());
        return model;
    }

    // --- 2. Request DTO -> Entity (Used for creating a new Service via API) ---
    public ServicesEntity toEntity(ServicesRequestDTO dto) {
        ServicesEntity entity = new ServicesEntity();
        // ID is left null, assuming it is generated by the database
        entity.setService_name(dto.getName());
        return entity;
    }

    // --- 3. Domain Model -> Entity (Used for updating an existing service) ---
    public ServicesEntity toEntity(ServicesModel model) {
        ServicesEntity entity = new ServicesEntity();
        entity.setService_id(model.getId());
        entity.setService_name(model.getName());
        return entity;
    }

    // --- 4. Entity -> Response DTO (Used for API responses) ---
    public ServicesResponseDTO toDto(ServicesEntity entity) {
        ServicesResponseDTO dto = new ServicesResponseDTO();
        dto.setId(entity.getService_id());
        dto.setName(entity.getService_name());
        return dto;
    }
}